import "./Note.css";
import { notes, settings, timelineItemsByNote } from '../../stores';
import { A, useNavigate } from '@solidjs/router';
import { useChildRoute } from '../ChildRoute';
import { createMemo, For, type JSX, Match, Show, Switch } from 'solid-js';
import { filetypeFromExt, YouTubeThumbURL } from "../../lib/filetypeFromExt";

export interface NoteProps {
    id: string; // generated by CanonicalNote internally
    title: string;
    details: {
        text: string;
        urls?: string[];
        [key: string]: any; // allow extra metadata if needed
    };
}

export class Note implements NoteProps {
    id: string; // generated by CanonicalNote internally
    title: string;
    details: {
        text: string;
        urls?: string[];
        [key: string]: any; // allow extra metadata if needed
    };

    private static ImageButton(props: { id: string }) {
        const navigate = useNavigate();
        const { childRoute } = useChildRoute();

        return (
            <button class="transparent square extra" onClick={() => navigate(childRoute('note/' + props.id))}>
                <img class="responsive" alt={notes[props.id].title}
                    src={notes[props.id].details.urls![0]}
                />
            </button>
        )
    }

    static Compact(props: { id: string }) {
        const navigate = useNavigate();
        const { childRoute } = useChildRoute();
        const link = () => childRoute('note/' + props.id);

        if (settings.noteChipsAsPics && notes[props.id].details.urls) {
            return <Note.ImageButton id={props.id} />;
        }

        return (
            <button onClick={() => navigate(link())} class="circle note"
                style={{
                    color: notes[props.id].details.clr,
                    "background-color": notes[props.id].details.clr,
                }}
            >
                <em>&</em>
                {/* <Note.Tooltip id={props.id} align="left" /> */}
            </button>
        );
    }

    static Chip(props: {
        id?: string,
        addToId?: string,
        fill?: boolean,
        index?: number,
    }) {
        const navigate = useNavigate();
        const { childRoute } = useChildRoute();
        if (props.id) {
            if (settings.noteChipsAsPics && notes[props.id].details.urls) {
                return <Note.ImageButton id={props.id} />;
            }

            return (
                <button class="note chip small" style={
                    `--this-clr:${notes[props.id].details.clr}`
                    + (props.fill ? `;background-color:${notes[props.id].details.clr}` : '')
                } onClick={() => navigate(childRoute('note/' + props.id))}
                >
                    <span>&{notes[props.id].title}</span>
                    {/* <Note.Tooltip id={props.id} align={props.index === 0? "right" : "bottom"} /> */}
                </button>
            );
        }

        return (
            <button class="note chip small" onClick={() => navigate(childRoute(`/attach-new/note/${props.addToId}`))} >
                <i>add</i>
                <span>Add Note</span>
            </button>
        );
    }

    static ListNotes = (props: { id?: string }) => {
        const { childRoute } = useChildRoute();

        const tagValues = createMemo(() => {
            if (props.id && notes[props.id]) return [notes[props.id]];
            return Object.values(notes);
        });

        const renderItems = (tagId: string) => (
            <ul>
                <For each={timelineItemsByNote()[tagId] ?? []}>
                    {(item) => (
                        <li>
                            <A href={childRoute(`/notes/${tagId}`)}>
                                {item.title || "(no title)"}
                            </A>
                        </li>
                    )}
                </For>
            </ul>
        );

        return (
            <Show
                when={props.id}
                fallback={
                    <ul class="border list no-space">
                        <For each={tagValues()}>
                            {(tag) => (
                                <li>
                                    <strong>{tag.title}</strong>
                                    {renderItems(tag.id)}
                                </li>
                            )}
                        </For>
                    </ul>
                }
            >
                {renderItems(props.id!)}
            </Show>
        );
    };

    static revive(obj: any) {
        return new Note(obj);
    }

    constructor(obj: NoteProps) {
        this.id = obj.id;
        this.title = obj.title;
        this.details = obj.details;
    }

    static urlForInnerHtml(url: string, size = "tiny"): string {
        const typeOrThumb = filetypeFromExt(url);

        const escapeHtml = (str: string) =>
            str.replace(/&/g, "&amp;")
                .replace(/</g, "&lt;")
                .replace(/>/g, "&gt;")
                .replace(/"/g, "&quot;")
                .replace(/'/g, "&#039;");

        const openInNewWindowAttr = `onclick="window.open('${escapeHtml(url)}','_blank');" style="cursor:pointer; display:inline-block;"`;

        if (typeOrThumb === "image") {
            return `<a href="${escapeHtml(url)}" target="_blank">
                        <img class="responsive ${escapeHtml(size)}" src="${escapeHtml(url)}" alt="${escapeHtml(url)}"/>
                    </a>`;
        }

        if (typeOrThumb === "video") {
            return `<div ${openInNewWindowAttr}>
                        <video class="responsive ${escapeHtml(size)}" controls>
                            <source src="${escapeHtml(url)}"/>
                        </video>
                    </div>`;
        }

        if (typeOrThumb === "audio") {
            return `<div ${openInNewWindowAttr}>
                        <audio class="responsive ${escapeHtml(size)}" controls>
                            <source src="${escapeHtml(url)}"/>
                        </audio>
                    </div>`;
        }

        if (typeof typeOrThumb === "string" && typeOrThumb.startsWith("https://img.youtube.com")) {
            return `<a href="${escapeHtml(url)}" target="_blank">
                        <img class="responsive ${escapeHtml(size)}" src="${escapeHtml(typeOrThumb)}" alt="YouTube"/>
                    </a>`;
        }

        return escapeHtml(url);
    }

    urlForInnerHtml(size = "tiny"): string {
        if (!this.details.urls?.length) return "";
        const url = this.details.urls[0];
        return Note.urlForInnerHtml(url, size);
    }

    renderCompact() { return this.title; }
}

